### PR TITLE
apply the ERB template to YAML config

### PR DESCRIPTION
**Pull request by Tei1988**
apply the ERB template to YAML config.

We want to use adwords_api.yml like below:

``` yaml
:authentication:
  :method: OAuth2
  :oauth2_client_id: <%= ENV['ADWORDS_API_OAUTH2_CLIENT_ID'] %>
  :oauth2_client_secret: <%= ENV['ADWORDS_API_OAUTH2_CLIENT_SECRET'] %>
  :developer_token: <%= ENV['ADWORDS_API_DEVELOPER_TOKEN'] %>
...
```

Please give me any advices if the code becomes more better/acceptable.

### CODE REVIEW

**Comment by mcloonan** [comment]
Thanks for the suggestion, and for pre-emptively signing the form to allow me to accept your submission.

I will talk this over with the team before merging; it seems like it could be a useful enhancement.

**Comment by Tei1988** [comment]
Hi, @mcloonan 

I just want to know the state of this PR.
Thanks.

**Comment by mcloonan** [comment]
I apologize for the slow handling of this. I will take a look at this and the other outstanding pull requests early next week.

If you want a way around this issue in the meanwhile, you could configure your API manually when instantiating it rather than using a config file. See this example for a demonstration: https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201601/misc/use_runtime_config.rb

**Comment by mcloonan** [comment]
I don't want to introduce an extra layer of processing to the config file, and another dependency to the lib, when we already support this use case by allowing you to pass arguments without use of this file. Thank you for your ideas to help improve the library!

**Pull request closed without merging**
