### PR TITLE
Rails new + gem upgrade + version update

### PR DESCRIPTION
**Pull request by mjfaga**
The rails command wasn't working when attempting to start the service,
and the `script/rails server` didn't exist. Re-installed rails in repo,
cleaned up .gitignore, updated the gem version, and moved to latest
version of API.

### CODE REVIEW

**Comment by dklimkin** [comment]
Hi mjfaga,

This PR includes some of the files specific to your usage which we wouldn't want to include in the sample app. We'll make sure to schedule update to the latest Rails asap.

**Comment by mjfaga** [comment]
I'm happy to remove files you don't want if you list them out for me. Let me know what works.

**Comment by mjfaga** [comment]
Is it just the .keep files you want me to delete, or is these something else?

**Comment by dklimkin** [comment]
Hi Mark,

Sorry for the delay, the team was busy with the AdWords API launch.

I mostly meant Gemfile.lock but also things like ".idea" in .gitignore, it's hard to filter out all parts.
With the release now out we'll be working on the update for AoR and latest Rails shortly.

@mcloonan to follow this update.

**Comment by mjfaga** [comment]
No problem. Thanks for the heads up. I'll go ahead and close out this PR.

**Pull request closed without merging**
