### PR TITLE
Handle RateExceededError

### PR DESCRIPTION
**Pull request by ibiziiac-sv**

### CODE REVIEW

**Comment by mcloonan** [comment]
Hello,

Before I can accept any pull requests, I need to ask you to sign this form: https://cla.developers.google.com/about/google-individual

Thanks you.

**Comment by ibiziiac-sv** [comment]
Hello,

Thanks for the hint. I have signed the form

Best regards,

Ion Biziiac

**Comment by mcloonan** [comment]
Thank you. I will look at pulling this code and/or incorporating it into a release soon.

**Comment by mcloonan** [comment]
Closing this pull request. We may want to look into providing more context should the user encounter RateExceededErrors, but we wouldn't want to limit the scope to reports.

**Pull request closed without merging**
